---
spring:
    profiles:
        active: dev
    redis:
        host: localhost
        port: 6379



application:
            host:
                url: "http://localhost:8080/"
                errorUrl: "http://localhost:8080/error-message"

message:
        welcome: "Welcome to this short url service"
        idNotFoundMessage: "Sorry, We are not able to redirect, the url seems invalid"
        requestBodyMissing: "Request body is missing"